In [3]:
import pandas as pd
df = pd.read_csv('/workspaces/data_3500_sandbox/lecture_code/titanic.csv')
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [2]:

"""
Programming Activity 1

Using the Titanic dataset and the Pandas library, fill in any missing data cells in the 'ages' column with the median age.
"""

df["Age"] = df["Age"].fillna(df["Age"].median())
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [8]:
"""
Programming Activity 2

Using the Titanic dataset and the Pandas library, create a new column called 'FamilySize' and fill it with the size of the passenger's family.
"""

df["FamilySize"] = df["Name"].notna().astype(int) + df["SibSp"]
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,FamilySize
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S,1
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S,1
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,1,2,W./C. 6607,23.4500,NaN,S,2
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C,1
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q,1

In [10]:
"""
Programming Activity 3

Using the Titanic dataset and the Pandas library, find the average survival rate by class and sex.
"""

survival_rate = df.groupby(["Pclass", "Sex"])["Survived"].mean()
print("Avg survival rate by class and sex: ", survival_rate)

Avg survival rate by class and sex:  Pclass  Sex
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: Survived, dtype: float64

In [12]:
"""
Programming Activity 4

Using the Titanic dataset and the Pandas library, find the average fare per class.
"""

Avg_Fare_Per_Class = df.groupby(["Pclass"])["Fare"].mean()
print(Avg_Fare_Per_Class)

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [14]:
"""
Programming Activity 5

Using the Titanic dataset and the Pandas library, find the median age of survivors versus non-survivors.
"""
df["Survived"] = df["Survived"].map({0: "Did Not Survive", 1: "Survived"})

Median_Age = df.groupby(["Survived"])["Age"].median()
print(Median_Age)

Survived
Did Not Survive    28.0
Survived           28.0
Name: Age, dtype: float64

In [4]:
df2 = pd.read_csv('/workspaces/data_3500_sandbox/lecture_code/SLC_weather.csv')
df2

,Date,Max Temp,Min Temp,Avg Temp,Departure,HDD,CDD,Precipitation,New Snow,Snow Depth
0,10/1/2025,76,52,64.0,2.6,1,0,0,0,0
1,10/2/2025,84,57,70.5,9.6,0,6,0,0,0
2,10/3/2025,85,57,71.0,10.6,0,6,0.14,0,0
3,10/4/2025,57,46,51.5,-8.4,13,0,2.47,0,0
4,10/5/2025,59,47,53.0,-6.5,12,0,T,0,0
5,10/6/2025,61,42,51.5,-7.5,13,0,0,0,0
6,10/7/2025,64,43,53.5,-5.0,11,0,0,0,0
7,10/8/2025,72,45,58.5,0.5,6,0,0,0,0
8,10/9/2025,84,54,69.0,11.4,0,4,T,0,M
9,10/10/2025,77,58,67.5,10.4,0,3,0.27,0,M
10,10/11/2025,77,42,59.5,2.8,5,0,0.6,0,M
11,10/12/2025,58,42,50.0,-6.2,15,0,0,0,0
12,10/13/2025,71,45,58.0,2.3,7,0,0.1,0,0
13,10/14/2025,72,52,62.0,6.7,3,0,0.73,0,0
14,10/15/2025,59,46,52.5,-2.4,12,0,0.03,0,0
15,10/16/2025,54,40,47.0,-7.4,18,0,0.61,0,0
16,10/17/2025,59,41,50.0,-4.0,15,0,0,0,0
17,10/18/2025,63,44,53.5,0.0,11,0,0,0,0
18,10/19/2025,75,46,60.5,7.4,4,0,T,0,0
19,10/20/2025,55,41,48.0,-4.7,17,0,T,0,0
20,10/21/2025,59,37,48.0,-4.3,17,0,0,0,0
21,10/22/2025,62,39,50.5,-1.4,14,0,0,0,0
22,10/23/2025,63,45,54.0,2.6,11,0,0,0,0
23,10/24/2025,63,41,52.0,1.0,13,0,0,0,0
24,10/25/2025,69,45,57.0,6.4,8,0,0,0,0
25,10/26/2025,65,45,55.0,4.8,10,0,0.1,0,0
26,10/27/2025,50,34,42.0,-7.8,23,0,0.07,0,0
27,10/28/2025,51,30,40.5,-8.9,24,0,0,0,0
28,10/29/2025,57,34,45.5,-3.5,19,0,0,0,0
29,10/30/2025,58,35,46.5,-2.1,18,0,0,0,0
30,10/31/2025,60,40,50.0,1.8,15,0,0,0,0

In [21]:
"""
Programming Activity 6
Using the weather file (located on week 11 programming activities page), find the longest warm streak where the high temperature was above 65 degrees.

"""
Temp_Streak = df2["Max Temp"]

df2["Warm"] = df2["Max Temp"] > 65
df2["Streak"] = (df2["Warm"] != df2["Warm"].shift()).cumsum()

Streaks = df2[df2["Warm"]].groupby("Streak").size()

Long_Streak = Streaks.max()
print("The longest streak of days over 65 degrees was", Long_Streak, "days.")

The longest streak of days over 65 degrees was 4 days.

In [6]:
"""
Programming Activity 7

Using the same weather dataset, find the hottest day and the coldest night.
"""

Warmest_IDX = df2["Max Temp"].idxmax()
Coldest_IDX = df2["Min Temp"].idxmin()

Warmest_Day = df2.loc[Warmest_IDX]
Coldest_Day = df2.loc[Coldest_IDX]

print("The warmest day of the year was: ", Warmest_Day)
print("The coldest day of the year was: ", Coldest_Day)

The warmest day of the year was:  Date             10/3/2025
Max Temp                85
Min Temp                57
Avg Temp              71.0
Departure             10.6
HDD                      0
CDD                      6
Precipitation         0.14
New Snow                 0
Snow Depth               0
Name: 2, dtype: object
The coldest day of the year was:  Date             10/28/2025
Max Temp                 51
Min Temp                 30
Avg Temp               40.5
Departure              -8.9
HDD                      24
CDD                       0
Precipitation             0
New Snow                  0
Snow Depth                0
Name: 27, dtype: object

In [10]:
"""
Programming Activity 8
Using the same weather dataset, find the single most volatile day (the day with the biggest difference between high and low temperature).

"""

Temp_Diff = (df2["Max Temp"] - df2["Min Temp"]).max()
Temp_Diff_Date = df2.loc[(df2["Max Temp"] - df2["Min Temp"]).idxmax(), "Date"]

print("The largest temperature difference in one day was", Temp_Diff, "degrees, and it was on", Temp_Diff_Date)

The largest temperature difference in one day was 35 degrees, and it was on 10/11/2025